language: python
dist: trusty
sudo: false
cache: pip

stages:
  - check
  - build

python:
  - '3.6'
  - '3.7-dev'
  - 'nightly'

jobs:
  include:
    - stage: check
      python: '3.6'
      script:
        - black --check futaba
    - stage: build
      script:
        # Display all lints and a report
        # Only fail on errors
        - pylint --reports=yes futaba || true
        - pylint --errors-only futaba

matrix:
  allow_failures:
    - python: 'nightly'
  fast_finish: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

notifications:
  email:
    on_success: never
    on_failure: always
